Task11: upload and download endpoint
Maksim7398/shop_task pull request #12
Opened 2024-01-03 09:14 UTC by Maksim7398

@GUR-ok

2024-01-22 16:15 UTC, GUR-ok requested changes

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
> +    @GetMapping(value = "/downloadFile", produces = {"application/octet-stream"})
/download

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
> +    @SneakyThrows
Не используй sneaky throws. Все checked исключения обрабатывай в свои кастмоные

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
> +        Resource resource = new UrlResource(file.toURI());
Давай лучше через сразу  Resource resource = new FileUrlResource(fileName);
И это нужно делать в сервисе

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
> +    @PostMapping("/uploadFile")
/upload

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
>  @RestController
У контроллера давай тоже интерфейс и импл

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +    private String PATH_FILE;
Лучше DOCUMENT_PATH. Чтобы соответствовало проперти в конфигах

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +            final List<String> listFiles = Arrays.stream(files).filter(file -> file.isFile() && file != null)
file != null тебе идея не подсвечивает? Выглядит бессмысленно, тк если нулл, но упадет на file.isFile(). И кажется в этом массиве не будет нулов.

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        return getFile.orElseThrow(() -> new FileNotFoundException("Файла с таким именем не существует"));
Сделай свой DocumentNotFoundException и обработай его тут try-catchem и снаружи хендлером

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/DocumentController.java
> +        headers.setContentDisposition(ContentDisposition.attachment().filename(file.getName()).build());
имя файла можно будет получить из ресурса

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/exception/GlobalExceptionHandlerController.java
> +    public ResponseEntity<ErrorDetails> handleFileNotFoundException(FileNotFoundException exception) {
Здесь хендлить нужно свой кастомный FileNotFoundException

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        Optional<File> getFile = Arrays.stream(files).filter(file -> file.getName().contains(fileName)).findFirst();
Не нужно проходиться по всем файлам в папке. Создай объект типа File у которого в конструктор передай PATH+fileName. Вообще здесь будет создаваться ресурс в который сразу можно подать PATH+name (см замечания контроллера)

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        return "Файл успешно загружен!";
Не, давай такое не будем возвращать. Лучше пустоту или просто полный путь к файлу с именем.

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        final File FOLDER = new File(PATH_FILE);
1. Нужно проверить есть ли такая директория, если нет, то создавать ее.
2. ```try {
			if (file.isEmpty()) {
				throw new StorageException("Failed to store empty file.");
			}
			Path destinationFile = this.rootLocation.resolve(
					Paths.get(file.getOriginalFilename()))
					.normalize().toAbsolutePath();
			try (InputStream inputStream = file.getInputStream()) {
				Files.copy(inputStream, destinationFile,
					StandardCopyOption.REPLACE_EXISTING);
			}
		}```

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +            ex.printStackTrace();
Стектрейс не выводят. Просто выводи в log.error какое-нибудь сообщение или выбрасывай кастомное исключение.

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        final File FOLDER = new File(PATH_FILE);
https://spring.io/guides/gs/uploading-files/ читай надежные источники

2024-01-22 16:15 UTC, GUR-ok commented on src/main/java/com/example/shop/service/product/ProductServiceImpl.java
> +<<<<<<< HEAD
Не должно быть незарезолвленных конфликтов! Просматривай сам свои МРы перед сдачей

2024-01-22 18:16 UTC, Maksim7398 commented on src/main/java/com/example/shop/service/document/FileServiceImpl.java
> +        Optional<File> getFile = Arrays.stream(files).filter(file -> file.getName().contains(fileName)).findFirst();
можно сразу ресурс создать, но если такого файла в папке не будет, то он выдаст ошибку 500

2024-01-23 11:08 UTC, GUR-ok approved these changes

2024-01-29 10:28 UTC, merged