Feature/task1
Maksim7398/shop_task pull request #3
Opened 2023-11-27 07:23 UTC by Maksim7398

@GUR-ok

2023-11-27 17:41 UTC, GUR-ok requested changes

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/ShopTask1Application.java
> +		System.out.println("hello world");
sout убрать

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/ShopTask1Application.java
>  package com.example.Shop_task1;
тут не будет разделения по таскам. Назови пакеты com.example.shop

2023-11-27 17:41 UTC, GUR-ok commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
Зачем эта зависимость?

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/ShopTask1Application.java
Давай назовем просто ShopApplication

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +import org.springframework.web.bind.annotation.*;
схлопнутых импортов быть не должно. настрой идею

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @GetMapping("/all_products")
"/products"

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @PostMapping("/create_product")
/product

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @GetMapping("/delete/{id}")
/product/{id}

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @GetMapping("/{id}")
/product/{id}

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @GetMapping("/delete/{id}")
Почитай про архитектруный стиль рест и прсивоение урлов эндпоинтам

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @PutMapping("/update/{id}")
/product/{id}

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +             return new ResponseEntity<>(HttpStatus.NOT_FOUND);
давай не 404 а 204 (No content)

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +
пустые строки убрать. посмотри везде плз!

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/controller/ProductController.java
> +    @ExceptionHandler(ProductNotFoundExeption.class)
exсeption handler должен быть в отдельном классе, не в контроллере

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/Categories.java
> +
пустая строка не нужна

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/Categories.java
> +
лищняя пустая строка

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +    @NotEmpty
NotEmpty тут убрать. валидацию делаем на реквестах контроллера

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/liquibase.properties
> +url=jdbc:postgresql://localhost:5432/product_store
файл не нужен

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +    private LocalDate exchangeCount;
LocalDateTime

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +    private LocalDate createDate;
LocalDateTime

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="create_date" type="date"/>
TIMESTAMP, еще добавить везде remarks с описанием. и констрейнт на nullable=false где нужно

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +    <changeSet author="user (generated)" id="1701031750600-1">
id="001-create-table-product" и автора себя добавь)

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="id" type="UUID">
айдишник для удобства перенести на первое место

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="price" type="FLOAT8"/>
DOUBLE PRECISION

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="exchange_count" type="date"/>
название exchange_count кажется странным. давай хотя бы last_quantity_change. ну и TIMESTAMP

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="description" type="VARCHAR(255)"/>
для description давай 1000 символов

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-outputChangeLog.xml
> +    <changeSet author="user (generated)" id="1700895869026-1">
автора и айди дать нормальные

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/application.yml
> +      ddl-auto: none
ddl-auto: validate

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/application.yml
> +    enabled: false
enabled: true

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/data.sql
> +insert into product (title, description, categories, price, count, exchange_count, create_date) values ('Pastry - Banana Tea Loaf', 'est quam pharetra magna ac consequat metus sapien ut nunc','BREAD'
data sql перенести в ресурсы и вызвать его из ченджсета 002-init-records

2023-11-27 17:41 UTC, GUR-ok commented on src/main/resources/application.yml
> +server:
```
server:
    servlet:
      context-path: /my-app
    port: 8085
```
И еще добавить конфиг логирования
```
  logging:
    level:
      root: INFO
      org.springframework: INFO
      com.example.shop: DEBUG
```

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +    Logger logger = Logger.getLogger(ProductService.class.getSimpleName());
Давай использовать @Slf4j логгер

2023-11-27 17:41 UTC, GUR-ok commented on target/generated-sources/annotations/com/example/Shop_task1/mapper/ProductMapperImpl.java
> +@Generated(
Автогенерируемых классов не должно быть в репозитории

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +    private int count;
Если у тебя поле nullable то лучше примитив не использовать. А вообще 
    @Column(name = "quantity", nullable = false)
    private Integer quantity

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +    @UpdateTimestamp
Здесь не UpdateTimeStamp. Эта дата должна менять только когда меняется количество. а это не при любом апдейте. Учесть в бизнес-логике сервиса

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductRepository.java
> +    List<ProductEntity> findAll();
Эти методы не нужны и доступны из коробки у JpaRepository

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/dto/CreateProductRequest.java
> +
Вот тут будет валидация. @NotBlank(message = "title must not be blank"). Повесить на те поля, которые не могут быть пустые. Проверить, передав в постмане пробелы в поле title

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/dto/CreateProductRequest.java
> +    private Double price;
@Positive(message = "Price should be at least 0 or higher")

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/dto/CreateProductRequest.java
> +
@NotNull над Categories

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/dto/GetProductResponse.java
> +   private LocalDate exchangeCount;
ФОрматирования поехало. Привыкай ctrl+alt+O и ctrl+alt+L

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/exeption/ProductNotFoundExeption.java
> +    public ProductNotFoundExeption(String id) {
Пусть сообщение принимает а не айди. ну и в супер передает просто это сообщение

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +        return mapper.getProduct(repository.findById(UUID.fromString(id)).orElseThrow(
тут не нужно uuid в строку преобразовывать

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +        return productEntity.getId();
return отделять пустой строкой, если в методе есть еще строки кроме return

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +        ProductEntity productEntity = mapper.createProductRequest(product);
Все переменные при объявлении final, все аргументы в методах - final. Поправь везде плз.

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +
По две пустых строки не делать

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +        } catch (ProductNotFoundExeption ex) {
тут странное с кэчем и пробросом исключения. не нужно ничего кэчить. в контроллере отловится

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +    public void deleteProdById(String id) {
deleteProductById

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +    public GetProductResponse getProductById(String id) {
Лучше чтобы сервисные методы не возвращали объекты, которые относятся к веб слою. Так делают часто, но тут давай не будем. Пусть возвращается productDto. Создай такой класс в пакете model (просил создать выше)

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/service/ProductService.java
> +            getProductById(id);
ты вызываешь метод  getProductById, в котором есть лишняя конвертация, котоаря тут совсем не нужна. вызови ездесь просто repository.findById(id).orElseThrow(

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductEntity.java
> +package com.example.Shop_task1.data;
вынести entity в пакет persist.entity

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/ProductRepository.java
> +@Repository
вынести репозиторий в пакет persist.repository

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/dto/CreateProductRequest.java
> +
Давай в пакете контроллер создадим два пакета: reqeust, response. И вытащим туда соотвтественно

2023-11-27 17:41 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/Categories.java
> +public enum Categories {
в пакет model на уровне com.example.shop

2023-11-27 17:49 UTC, GUR-ok commented on src/main/java/com/example/Shop_task1/data/Categories.java
> +public enum Categories {
Название должно быть в едиснтвенном числе Category

2023-11-27 17:50 UTC, GUR-ok commented on src/main/resources/application.yml
> +    username: user
А где пассворд?

2023-11-27 17:56 UTC, GUR-ok requested changes
Коллекцию запросов постман приложить к проекту. В постмане написать простые постман-тесты (за примерами обращайся), чтобы коллекцию можно было прогнать разом всю. Коллекция запросов - create, get, update, get с тестом что поле изменилось, delete с проверкой на 200, гет для подверждения что удалилось. Ну и create с невалидным полем чтобы проверить 400.

2023-11-27 18:25 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="price" type="FLOAT8"/>
numeric тип следует выбирать для хранения денежных сумм, а также в других случаях, когда требуется гарантировать точность вычислений.

2023-11-27 21:06 UTC, Maksim7398 commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +            <column name="price" type="FLOAT8"/>
поздно увидел, сейчас исправлю

2023-11-27 21:08 UTC, Maksim7398 commented on src/main/resources/application.yml
> +    username: user
пароль забыл, пришлось вообще его убрать
позже поставлю

2023-11-27 21:09 UTC, Maksim7398 commented on src/main/java/com/example/Shop_task1/data/Categories.java
> +public enum Categories {
Исправил, поздно увидел

2023-11-29 10:45 UTC, GUR-ok requested changes

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/persist/entity/ProductEntity.java
> +import jakarta.persistence.*;
импорты

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/GlobalExceptionHandlerController.java
> +    public String handleEmptySearchException(ProductNotFoundExeption exception) {
Вовзращать стрингу тут не совсем верно. Нужно ResponseEntity вовзращать. Поправим в задании 3. Пока оставим так.

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/model/ProductDto.java
> +    private final UUID id;
Поля, которые могут быть null пометить спринговой аннотаций Nullable. Добавить в пакет service файл `package-info.java` со след.содержимым:
```@NonNullApi
package ru.ncs.DemoShop.controller.advice;

import org.springframework.lang.NonNullApi;

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/model/ProductDto.java
> +    private final UUID id;
можео будет созвониться, расскажу зачем это нужно

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/persist/entity/ProductEntity.java
> +    @Column(name = "description",nullable = false)
давай description сделаем nullable, в скриптах миграции там ок

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/service/ProductService.java
> +    public final UUID save(final CreateProductRequest product) {
final CreateProductRequest request

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/service/ProductService.java
> +    public final ProductDto updateProduct(final UUID id, final CreateProductRequest p) {
final CreateProductRequest request

2023-11-29 10:45 UTC, GUR-ok commented on src/main/java/com/example/shop/service/ProductService.java
> +        log.info(productEntity.toString());
log.debug

2023-11-29 10:50 UTC, GUR-ok requested changes

2023-11-29 10:50 UTC, GUR-ok commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
Ты ее не убрал?

2023-11-29 10:50 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/request/CreateProductRequest.java
> +    @NotBlank(message = "categories must not be blank")
NotBlank только для стрингов. Для енума пусть будет NotNull

2023-11-29 10:50 UTC, GUR-ok commented on src/main/java/com/example/shop/model/ProductDto.java
> +@Data
Давай ломбоковское Value вместо Data

2023-11-30 14:03 UTC, merged