Task2:add new profile and new article
Maksim7398/shop_task pull request #4
Opened 2023-12-01 08:16 UTC by Maksim7398

@GUR-ok

2023-12-03 08:23 UTC, GUR-ok requested changes

2023-12-03 08:23 UTC, GUR-ok commented on pom.xml
> +		<java.version>11</java.version>
Почему решил сменить версию?

2023-12-03 08:23 UTC, GUR-ok commented on pom.xml
> +			<version>1.5.3.Final</version>
Эти изменения опять попали в пр. Вмержи девелоп в свою ветку или сделай ребейз коммитов из второй задачи. Плюс у тебя конфликты, их нужно пофиксить

2023-12-04 06:04 UTC, GUR-ok requested changes

2023-12-04 06:04 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +                <constraints  unique="true" nullable="false"/>
А что будет если отправить запрос на создание товара с существующим article? Или при апдейте товара поставить ему article неуникальны? В апдейте кстати вообще вроде нельзя преедать article. Должна быть проверка в бизнес логике в сервисном слое, что такого article нет в бд. Для учебных целей давай при апдейте проверять артикул через hql запрос вида
```
@Query(
        """
            select case when (count(p) > 0) then false else true end 
            from products p
            where p.article = :article
        """
    )
    fun isArticleExist(
        article: String,
    ): Boolean
``` либо просто existsByArticle jpa метод без query.
    , а при создании проверять по findById+обработку через optional. Бросать кастомное ArticleAlreadyExistsException

2023-12-04 06:07 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/ProductController.java
>      public GetProductResponse updateProduct(@RequestBody CreateProductRequest product, @PathVariable UUID id) {
Для метода апдейт должен быть свой UpdateProductRequest

2023-12-04 15:13 UTC, GUR-ok requested changes

2023-12-04 15:13 UTC, GUR-ok commented on src/main/java/com/example/shop/model/sheduler/ProductPriceIncreaseScheduler.java
> +public class ProductPriceIncreaseScheduler {
шедулер это 4я задача. ПР на 2ю

2023-12-04 15:13 UTC, GUR-ok commented on src/main/java/com/example/shop/exeption/GlobalExceptionHandlerController.java
> +    @ExceptionHandler
handler это 3я задача, сдаем 2ю

2023-12-04 15:13 UTC, GUR-ok commented on src/main/java/com/example/shop/persist/repository/ProductRepository.java
> +    Optional<ProductEntity> findByArticle(String article);
Где метод  existsByArticleCustom (или на край existsByArticle (предоставит jpa-repository только исходя из нейминга). Подробнее тут https://www.baeldung.com/spring-data-exists-query и еще писал ниже. Почитай как можно формировать запросы к jpa репозитолрию через нейминг (например можно сортировку по параметру задавать и поиск по неск.параметрам)

2023-12-04 15:13 UTC, GUR-ok commented on src/main/java/com/example/shop/service/ProductService.java
> +            final ProductEntity productEntity = mapper.createProductRequest(request);
чет форматирование поехало. юзай ctrl+alt+o  и ctrl+alt+L

2023-12-04 15:13 UTC, GUR-ok commented on src/main/resources/application.yml
> +    active: local
активный профиль отсюда убрать. активировать при запуске через environment variables указав --spring.profiles.active=local

2023-12-04 15:13 UTC, GUR-ok commented on src/main/resources/application.yml
> +app:
шедулинг из другой задачи. необходимо убрать

2023-12-04 15:13 UTC, GUR-ok commented on src/main/resources/db/changelog/liquibase-initDB.xml
> +                <constraints  unique="true" nullable="false"/>
не увидел метода в репозитории

2023-12-05 04:47 UTC, GUR-ok requested changes

2023-12-05 04:47 UTC, GUR-ok commented on src/main/java/com/example/shop/ShopApplication.java
> +@EnableScheduling
Шедулинг не в этой задаче

2023-12-05 04:47 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/ProductController.java
>      @SneakyThrows
А зачем тут @SneakyThrows? Ты знаешь что это означает?

2023-12-05 04:47 UTC, GUR-ok commented on pom.xml
> +			<groupId>net.javacrumbs.shedlock</groupId>
Шедулинг не в этой задаче

2023-12-05 06:00 UTC, Maksim7398 commented on src/main/java/com/example/shop/controller/ProductController.java
>      @SneakyThrows
Да, знаю . Исключение пробрасывает

2023-12-05 06:16 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/ProductController.java
>      @SneakyThrows
оно маскирует чекед эксепшн в анчекед.. тут мне кажется не нужно

2023-12-05 06:17 UTC, GUR-ok commented on src/main/java/com/example/shop/controller/ProductController.java
>          return ResponseEntity.ok(mapper.convertFromDto(service.getProductById(id))).getBody();
Тут лишние операции. ты создаешь ResponseENtity, а потом у него боди выдергиваешь. Можно просто ResponseEntity не создавать)

2023-12-05 11:05 UTC, GUR-ok approved these changes

2023-12-05 11:07 UTC, merged